FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.0

RUN bin/elasticsearch-plugin install https://github.com/papahigh/elasticsearch-russian-phonetics/raw/7.3.0/esplugin/plugin-distributions/analysis-russian-phonetic-7.3.0.zip

