version: '2.4'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=catalog
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432

  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ${PWD}/build/wiremock/all_in_one:/home/wiremock
    ports:
      - ${WIREMOCK_EXTERNAL_PORT}:8080
    command: [ "java", "-cp", "/var/wiremock/lib/*:/var/wiremock/extensions/*", "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner", "--local-response-templating", "--disable-banner", "--no-request-journal" ]

  es01:
    image: elastic_rus_phonetic:7.3.0
    container_name: es01
    environment:
      - discovery-type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_S1_EXTERNAL_PORT}:9200
  es02:
    image: elastic_rus_phonetic:7.3.0
    container_name: es02
    environment:
      - discovery-type=single-node
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_S2_EXTERNAL_PORT}:9200

volumes:
  postgres-db:
    driver: local